name: Tag master
on:
  pull_request:
    branches: [ master ]
    types: [ closed ]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Tag Master
        uses: stream-monkey/actions/tag@master
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"